/* 테이블 생성 */  
CREATE TABLE members(
    userid             VARCHAR2(30)    PRIMARY KEY, 
    userpw             VARCHAR2(200)   NOT NULL,
    authority           VARCHAR2(20)    DEFAULT 'ROLE_USER',
    enabled             NUMBER(1)       DEFAULT 1,
    username  VARCHAR2(100)   UNIQUE,
    phonenumber        VARCHAR2(20)    UNIQUE,
    email               VARCHAR2(100)   UNIQUE,
    address             VARCHAR2(200),
    profileimgpath      VARCHAR2(100)
);

CREATE TABLE hboard (
  boardidx     NUMBER          PRIMARY KEY,
  userid       VARCHAR2(30)    NOT NULL,
  title        VARCHAR2(100)   NOT NULL,
  content      CLOB            NOT NULL,
  ofile        VARCHAR2(255),
  sfile        VARCHAR2(255),
  postdate     DATE            DEFAULT SYSDATE,              
  category     NUMBER(1)       DEFAULT 1 CHECK (category IN (1, 2)),
  visitcount   NUMBER          DEFAULT 0,  
  likes        NUMBER          DEFAULT 0,
  report       NUMBER          DEFAULT 0,
  CONSTRAINT fk_board_member FOREIGN KEY (userid) REFERENCES members(userid)
);


CREATE TABLE comments (
  commentidx   NUMBER PRIMARY KEY,
  userid       VARCHAR2(30)  NOT NULL,
  boardidx     NUMBER NOT NULL,
  likes        NUMBER          DEFAULT 0,
  content      VARCHAR2(500) NOT NULL,
  postdate    DATE DEFAULT SYSDATE,
  CONSTRAINT fk_comment_board FOREIGN KEY (boardidx) REFERENCES hboard(boardidx),
  CONSTRAINT fk_comment_member FOREIGN KEY (userid) REFERENCES members(userid)
);


CREATE TABLE diary (
  diaryidx      NUMBER          PRIMARY KEY,   
  userid        VARCHAR2(30)          NOT NULL,
  ofilename     VARCHAR2(255),     
  sfile         VARCHAR2(255),     
  postdate      DATE            DEFAULT SYSDATE,
  description   VARCHAR2(500),                  
  temperature   NUMBER(5, 2),        
  humidity      NUMBER(5, 2),      
  sunlight      NUMBER(5, 2),   
  height        NUMBER(5,2),
  fruit         NUMBER,
  plantidx     NUMBER,  -- 선택 시에만 저장 (NULL 허용)
  CONSTRAINT fk_diary_member FOREIGN KEY (userid) REFERENCES members(userid),
  CONSTRAINT fk_diary_plantdict FOREIGN KEY (plantidx)
    REFERENCES plantdict(plantidx) ON DELETE SET NULL
);



CREATE TABLE plantdict (
  plantidx          NUMBER          PRIMARY KEY,
  name              VARCHAR2(100)   NOT NULL,
  engname           VARCHAR2(100)   NOT NULL,
  category          VARCHAR2(100)   NOT NULL,
  imgpath           VARCHAR2(255)   NOT NULL,
  growseason        VARCHAR2(50),
  bloomingseason    VARCHAR2(50),
  sunlight          VARCHAR2(100),
  humidity          VARCHAR2(50),
  temperature       VARCHAR2(50),
  water             VARCHAR2(100),
  disease           VARCHAR2(100),
  summary           VARCHAR2(1000),
  note              VARCHAR2(500),
  postdate          DATE DEFAULT    SYSDATE
);



/*mbti*/
CREATE TABLE mbti (
  mbtiidx               NUMBER          PRIMARY KEY,    
  name                  VARCHAR2(50)    NOT NULL,
  imgFile               VARCHAR2(50),
  category              VARCHAR2(50)    NOT NULL,
  plants                VARCHAR2(100)    NOT NULL,
  character        VARCHAR2(100),
  growperiod            VARCHAR2(100),
  growenv               VARCHAR2(100),
  difflevel             VARCHAR2(100),
  reason                VARCHAR2(500)
);


CREATE TABLE hlike (
    LIKE_IDX NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOARD_IDX NUMBER NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    LIKED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT fk_hlike_board FOREIGN KEY (BOARD_IDX) 
        REFERENCES hboard(boardidx) ON DELETE CASCADE
);

/* 동수 게시판 이미지 테이블 추가 */
CREATE TABLE BOARD_IMAGE (
    IMAGE_IDX NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOARD_IDX NUMBER,
    ORIGINAL_NAME VARCHAR2(255),
    SAVED_NAME VARCHAR2(255),
    FILEPATH VARCHAR2(255),
    CONSTRAINT fk_BOARD_IMAGE_board FOREIGN KEY (BOARD_IDX) 
        REFERENCES hboard(boardidx) ON DELETE CASCADE
);

--동수가 추가
CREATE TABLE BOARD_REPORT (
    REPORT_IDX NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOARD_IDX NUMBER,
    USER_ID VARCHAR2(255),
    CONTENT VARCHAR2(255),
    REPORT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT fk_board_report_board FOREIGN KEY (BOARD_IDX) 
        REFERENCES hboard(boardidx) ON DELETE CASCADE
);

-- qnaBoard
CREATE TABLE qna_board (
    idx NUMBER PRIMARY KEY,                   -- 게시글 고유번호
    writerid VARCHAR2(100) NOT NULL,            -- 작성자 아이디 (FK 가능)
    writer VARCHAR2(100) NOT NULL,              -- 작성자 닉네임
    title VARCHAR2(255) NOT NULL,               -- 제목
    content CLOB NOT NULL,                      -- 본문 내용
    category VARCHAR2(50),                      -- 카테고리
    secretflag CHAR(1) DEFAULT 'N',              -- 비밀글 여부 (Y/N)
    noticeflag CHAR(1) DEFAULT 'N',           -- 공지글 여부 (Y/N)
    answerstatus VARCHAR2(20) DEFAULT '대기',    -- 답변 상태
    answercontent CLOB,                         -- 답변 내용
    views NUMBER DEFAULT 0,                     -- 조회수
    likes NUMBER DEFAULT 0,                     -- 좋아요 수
    postdate DATE DEFAULT SYSDATE,              -- 작성일
    updatedate DATE DEFAULT SYSDATE
);

/* 시퀀스 */
CREATE SEQUENCE board_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE comment_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE diary_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE plant_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  
CREATE SEQUENCE mbti_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
--동수가 추가
CREATE SEQUENCE REPORT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE qna_board_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


/* Trigger */  
CREATE OR REPLACE TRIGGER trg_qna_board_idx
BEFORE INSERT ON qna_board
FOR EACH ROW
BEGIN
    :NEW.idx := qna_board_seq.NEXTVAL;
END;
/


/* insert */
/* members */
INSERT INTO members (
  userid, userpw, authority, enabled, username, phonenumber, email, address
) VALUES (
  'hani', '1111', 'ROLE_USER', 1, 'hani', '010-1111-1111', 'hani@naver.com', 'Seoul'
);

INSERT INTO members (
  userid, userpw, authority, enabled, username, phonenumber, email, address
) VALUES (
  'cheon', '2222', 'ROLE_USER', 1, 'cheon', '010-2222-2222', 'cheon@google.com', 'Busan'
);

/* hboard */
INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '병충해 방제 질문',
        '상추 잎에 작은 점이 생겼는데 방제 방법 추천 부탁드려요.', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '물주기 주기 어느 정도가 적당할까요?',
        '실내 화분(몬스테라) 기준으로 주 몇 회가 좋은지 경험 공유 부탁드려요.', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '텃밭 첫파종 후기',
        '상추/바질 파종했는데 발아율 괜찮네요. 흙 배합은 상토7+펄라이트2+질석1 사용.', 2);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'cheon',
        'LED 식물등 추천 좀',
        '창문이 북향이라 광량이 부족해요. 전력 20~30W대 사용해보신 분 있나요?', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'cheon',
        '해충 트랩 자작 후기',
        '노란 점착 트랩이 꽤 효과 있었어요. 붙은 개체 수가 확 줄었습니다.', 2);
        

/* 커밋 */
commit;

SELECT * FROM qna_board where noticeflag = 'N';

/* select */

select * from members;
select * from hboard;
select * from comments;
select * from diary;
select * from plantdict;
select * from mbti;

/* drop table */
DROP TABLE members CASCADE CONSTRAINTS;
DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE hboard CASCADE CONSTRAINTS;
DROP TABLE diary CASCADE CONSTRAINTS;
DROP TABLE plantdict CASCADE CONSTRAINTS;
DROP TABLE mbti CASCADE CONSTRAINTS;
DROP TABLE hlike CASCADE CONSTRAINTS;
/* 게시판 이미지 테이블 삭제 */
drop table BOARD_IMAGE;
DROP TABLE qna_board CASCADE CONSTRAINTS;

/* 시퀀스 삭제 */
DROP SEQUENCE plant_seq;
DROP SEQUENCE diary_seq;
DROP SEQUENCE board_seq;
DROP SEQUENCE comment_seq;
DROP SEQUENCE mbti_seq;
DROP SEQUENCE qna_board_seq;

/* admin으로 회원가입 한 후 밑의 코드를 삽입하면 admin계정이 ROLE_ADMIN으로 권한 변경*/
UPDATE members
SET authority = 'ROLE_ADMIN'
WHERE userid = 'admin';