/* 테이블 생성 */  
CREATE TABLE members(
    userid             VARCHAR2(30)    PRIMARY KEY, 
    userpw             VARCHAR2(200)   NOT NULL,
    authority           VARCHAR2(20)    DEFAULT 'ROLE_USER',
    enabled             NUMBER(1)       DEFAULT 1,
    username  VARCHAR2(100)   UNIQUE,
    phonenumber        VARCHAR2(20)    UNIQUE,
    email               VARCHAR2(100)   UNIQUE,
    address             VARCHAR2(200),
    profileimgpath      VARCHAR2(100)
);

CREATE TABLE hboard (
  boardidx     NUMBER          PRIMARY KEY,
  userid       VARCHAR2(30)    NOT NULL,
  title        VARCHAR2(100)   NOT NULL,
  content      CLOB            NOT NULL,
  ofile        VARCHAR2(255),
  sfile        VARCHAR2(255),
  postdate     DATE            DEFAULT SYSDATE,              
  category     NUMBER(1)       DEFAULT 1 CHECK (category IN (1, 2)),
  visitcount   NUMBER          DEFAULT 0,  
  likes        NUMBER          DEFAULT 0,
  report       NUMBER          DEFAULT 0,
  CONSTRAINT fk_board_member FOREIGN KEY (userid) REFERENCES members(userid)
);


CREATE TABLE comments (
  commentidx   NUMBER PRIMARY KEY,
  userid       VARCHAR2(30)  NOT NULL,
  boardidx     NUMBER NOT NULL,
  likes        NUMBER          DEFAULT 0,
  content      VARCHAR2(500) NOT NULL,
  postdate    DATE DEFAULT SYSDATE,
  CONSTRAINT fk_comment_board FOREIGN KEY (boardidx) REFERENCES hboard(boardidx),
  CONSTRAINT fk_comment_member FOREIGN KEY (userid) REFERENCES members(userid)
);


CREATE TABLE diary (
  diaryidx      NUMBER          PRIMARY KEY,   
  userid        VARCHAR2(30)          NOT NULL,
  ofilename     VARCHAR2(255),     
  sfile         VARCHAR2(255),     
  postdate      DATE            DEFAULT SYSDATE,
  description   VARCHAR2(500),                  
  temperature   NUMBER(5, 2),        
  humidity      NUMBER(5, 2),      
  sunlight      NUMBER(5, 2),   
  height        NUMBER(5,2),
  fruit         NUMBER,
  plantidx     NUMBER,  -- 선택 시에만 저장 (NULL 허용)
  CONSTRAINT fk_diary_member FOREIGN KEY (userid) REFERENCES members(userid),
  CONSTRAINT fk_diary_plantdict FOREIGN KEY (plantidx)
    REFERENCES plantdict(plantidx) ON DELETE SET NULL
);



CREATE TABLE plantdict (
  plantidx         NUMBER         PRIMARY KEY,
  name              VARCHAR2(100)  NOT NULL,
  imgpath             VARCHAR2(255),
  summary           VARCHAR2(500),
  note              VARCHAR2(1000),
  growseason       VARCHAR2(50),
  bloomingseason   VARCHAR2(50),
  humidity          VARCHAR2(50),
  sunlight          VARCHAR2(50),
  temperaturemin   NUMBER(5,2),
  temperaturemax   NUMBER(5,2),
  postdate          DATE DEFAULT SYSDATE
);



/*mbti*/
CREATE TABLE mbti (
  mbtiidx               NUMBER          PRIMARY KEY,    
  name                  VARCHAR2(50)    NOT NULL,
  imgFile               VARCHAR2(50),
  category              VARCHAR2(50)    NOT NULL,
  plants                VARCHAR2(100)    NOT NULL,
  character        VARCHAR2(100),
  growperiod            VARCHAR2(100),
  growenv               VARCHAR2(100),
  difflevel             VARCHAR2(100),
  reason                VARCHAR2(500)
);


CREATE TABLE hlike (
    LIKE_IDX NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOARD_IDX NUMBER NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    LIKED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT fk_hlike_board FOREIGN KEY (BOARD_IDX) 
        REFERENCES hboard(boardidx) ON DELETE CASCADE
);


/* 시퀀스 */
CREATE SEQUENCE board_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE comment_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE diary_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE plant_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  
CREATE SEQUENCE mbti_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  /* insert */
  /* members */
INSERT INTO members (
  userid, userpw, authority, enabled, username, phonenumber, email, address
) VALUES (
  'hani', '1111', 'ROLE_USER', 1, 'hani', '010-1111-1111', 'hani@naver.com', 'Seoul'
);

INSERT INTO members (
  userid, userpw, authority, enabled, username, phonenumber, email, address
) VALUES (
  'cheon', '2222', 'ROLE_USER', 1, 'cheon', '010-2222-2222', 'cheon@google.com', 'Busan'
);

/* hboard */
INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '병충해 방제 질문',
        '상추 잎에 작은 점이 생겼는데 방제 방법 추천 부탁드려요.', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '물주기 주기 어느 정도가 적당할까요?',
        '실내 화분(몬스테라) 기준으로 주 몇 회가 좋은지 경험 공유 부탁드려요.', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'hani',
        '텃밭 첫파종 후기',
        '상추/바질 파종했는데 발아율 괜찮네요. 흙 배합은 상토7+펄라이트2+질석1 사용.', 2);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'cheon',
        'LED 식물등 추천 좀',
        '창문이 북향이라 광량이 부족해요. 전력 20~30W대 사용해보신 분 있나요?', 1);

INSERT INTO hboard (boardidx, userid, title, content, category)
VALUES (board_seq.NEXTVAL, 'cheon',
        '해충 트랩 자작 후기',
        '노란 점착 트랩이 꽤 효과 있었어요. 붙은 개체 수가 확 줄었습니다.', 2);
        

/* plantdict */ 

-- 1. 상추
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '상추', 'lettuce.jpg',
  '봄~여름', NULL, '보통', '햇빛 많은 곳',
  15.0, 25.0, '잎채소의 대표주자로 초보자에게 적합하며 빠르게 수확 가능'
);

-- 2. 방울토마토
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '방울토마토', 'tomato.jpg',
  '봄~초여름', '6~7월', '보통~약간 건조', '햇빛 매우 많은 곳',
  20.0, 30.0, '달콤한 열매가 인기 많은 작물로 일조량이 매우 중요함'
);

-- 3. 바질
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '바질', 'basil.jpg',
  '여름', '7~8월', '높음', '반양지~햇빛 많은 곳',
  18.0, 30.0, '허브의 일종으로 물 빠짐 좋은 흙과 따뜻한 온도를 선호'
);

-- 4. 고추
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '고추', 'pepper.jpg',
  '봄~여름', '6~9월', '보통', '햇빛 많은 곳',
  18.0, 30.0, '한 번 심으면 오랫동안 수확 가능한 대표적인 열매채소'
);

-- 5. 애플민트
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '애플민트', 'applemint.jpg',
  '봄~가을', '6~8월', '높음', '반그늘~햇빛',
  15.0, 28.0,'실내에서도 잘 자라며 상쾌한 향으로 인기가 높음'
);
-- 8.9 추가
-- 6. 루꼴라
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '루꼴라', 'arugula.jpg',
  '봄~가을', '5~7월', '중간', '햇빛',
  10.0, 25.0, '샐러드나 파스타에 활용되며 특유의 향과 맛이 있음'
);
-- 7. 스테비아
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '스테비아', 'stevia.jpg',
  '봄~가을', '7~9월', '중간', '햇빛',
  15.0, 30.0, '천연 감미료로 사용되며 달콤한 잎을 가짐'
);
-- 8. 애플수박
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '애플수박', 'apple_watermelon.jpg',
  '봄~여름', '7~8월', '중간', '햇빛',
  20.0, 35.0, '작은 크기와 달콤한 맛으로 가정 재배에 적합'
);
-- 9. 무
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '무', 'radish.jpg',
  '봄~가을', '4~11월', '중간', '햇빛',
  5.0, 25.0,'재배가 쉽고 다양한 요리에 활용되는 뿌리채소'
);
-- 10. 대파
INSERT INTO plantdict (
 plantidx, name, imgpath, growseason, bloomingseason, humidity, sunlight,
  temperaturemin, temperaturemax, summary
) VALUES (
  plant_seq.NEXTVAL, '대파', 'green_onion.jpg',
  '봄~가을', '5~10월', '중간', '햇빛',
  10.0, 28.0,  '요리에 필수적인 향채로 사계절 재배 가능'
);

/* 커밋 */
commit;

/* select */

select * from members;
select * from hboard;
select * from comments;
select * from diary;
select * from plantdict;
select * from mbti;

/* drop table */
DROP TABLE members CASCADE CONSTRAINTS;
DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE hboard CASCADE CONSTRAINTS;
DROP TABLE diary CASCADE CONSTRAINTS;
DROP TABLE plantdict CASCADE CONSTRAINTS;
DROP TABLE mbti CASCADE CONSTRAINTS;
DROP TABLE hlike CASCADE CONSTRAINTS;

/* 시퀀스 삭제 */
DROP SEQUENCE plant_seq;
DROP SEQUENCE diary_seq;
DROP SEQUENCE board_seq;
DROP SEQUENCE comment_seq;
DROP SEQUENCE mbti_seq;

/* admin으로 회원가입 한 후 밑의 코드를 삽입하면 admin계정이 ROLE_ADMIN으로 권한 변경*/
UPDATE members
SET authority = 'ROLE_ADMIN'
WHERE userid = 'admin';
db 전체